/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBarcodesRouteImport } from './routes/api/barcodes'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiXlsxRouteImport } from './routes/api/xlsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBarcodesRoute = ApiBarcodesRouteImport.update({
  id: '/api/barcodes',
  path: '/api/barcodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXlsxRoute = ApiXlsxRouteImport.update({
  id: '/api/xlsx',
  path: '/api/xlsx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/barcodes': typeof ApiBarcodesRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/health': typeof ApiHealthRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/session': typeof ApiSessionRoute
  '/api/xlsx': typeof ApiXlsxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/barcodes': typeof ApiBarcodesRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/health': typeof ApiHealthRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/session': typeof ApiSessionRoute
  '/api/xlsx': typeof ApiXlsxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/barcodes': typeof ApiBarcodesRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/health': typeof ApiHealthRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/session': typeof ApiSessionRoute
  '/api/xlsx': typeof ApiXlsxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/barcodes'
    | '/api/catalog'
    | '/api/extract'
    | '/api/health'
    | '/api/login'
    | '/api/logout'
    | '/api/session'
    | '/api/xlsx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/barcodes'
    | '/api/catalog'
    | '/api/extract'
    | '/api/health'
    | '/api/login'
    | '/api/logout'
    | '/api/session'
    | '/api/xlsx'
  id:
    | '__root__'
    | '/'
    | '/api/barcodes'
    | '/api/catalog'
    | '/api/extract'
    | '/api/health'
    | '/api/login'
    | '/api/logout'
    | '/api/session'
    | '/api/xlsx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBarcodesRoute: typeof ApiBarcodesRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ApiXlsxRoute: typeof ApiXlsxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/barcodes': {
      id: '/api/barcodes'
      path: '/api/barcodes'
      fullPath: '/api/barcodes'
      preLoaderRoute: typeof ApiBarcodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xlsx': {
      id: '/api/xlsx'
      path: '/api/xlsx'
      fullPath: '/api/xlsx'
      preLoaderRoute: typeof ApiXlsxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBarcodesRoute: ApiBarcodesRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiSessionRoute: ApiSessionRoute,
  ApiXlsxRoute: ApiXlsxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
